name: Common Workflow

on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
  
jobs:
  job1:
    runs-on: windows-latest
    env:
       my_env_var: "Environment variable"    

    steps:
      - name: Print some info
        run: echo "job1 My env variable ${{ env.my_env_var }}" |
             echo 'job1 My env variable $my_env_var'

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - run: echo 'job2 version ${{ inputs.version }}'
